### ISSUE TITLE
next.js を build するときのキャッシュがない

### ISSUE THREAD

**Issue by onsd** [kanko-dori/favox#69]
## WHY

ビルド時に以下のような warn が出た

```
warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: err.sh/next.js/no-cache
```

## WHAT

https://github.com/vercel/next.js/blob/master/errors/no-cache.md によると、以下のような step を追加すればいいらしい
```yaml
uses: actions/cache@v2
with:
  path: ${{ github.workspace }}/.next/cache
  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
```
